import AuthProvider from "@/context/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "@/context/Themeprovider";
import ThemeSwitcher from "@/components/Switch/ThemeSwitcher";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{
      colorScheme: "light"
    }}>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider>
            <main className="bg-primary-1 h-full w-full">
              <Navbar />
              {children}
              <ThemeSwitcher />
            </main>
          </ThemeProvider>
        </AuthProvider>
        <Script src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></Script>
        <Script src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></Script>
      </body>
    </html>
  );
}
