import AuthProvider from "@/context/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "@/context/Themeprovider";
// import ThemeSwitcher from "@/components/Switch/ThemeSwitcher";
import Navbar from "@/components/Navbar/Navbar";
import { SiteFooter } from "@/components/Footer/SiteFooter";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
import { Analytics } from "@vercel/analytics/react";
export const metadata: Metadata = {
  title: "Taxonomy Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light"
      style={{
        colorScheme: "light",
      }}>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider>
            <main className="bg-primary-1 h-full w-full">
              <Navbar />
              <Toaster />
              <Analytics />
              {children}
              {/* <ThemeSwitcher /> */}
              <SiteFooter />
            </main>
          </ThemeProvider>
        </AuthProvider>
        <Script src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></Script>
        <Script src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></Script>
      </body>
    </html>
  );
}
